---
title: "Supplement 3.1"
author: "VKL"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning=FALSE,message=FALSE) 

library(tidyverse)
library(tidytext)
library(ggrepel)

library(gridExtra)
library(cowplot)
library(scoringutils)
library(viridis)

library(ggeffects)
library(emmeans)
library(splines)

setwd("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts")

### Need functions
source("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts/Code/Inc_Case_Eval_Manuscript/coverage.R") #coverage

## Standardized formatting
strip.background_standard <-element_blank()
strip.text_standard <-element_text(size=10, face='bold')
legend.text_standard <-element_text(size=12)
plot.caption_standard <-element_text(size=11, face = "italic")
axis.title.y_standard <-element_text(margin = margin(1, 10, 1, 1), size=12)
axis.text_standard <-element_text(size=11)


## Change labels for counties
 rename_counts <-function(df) {   
   df <-df %>%
     mutate(pop_size_quant2=ifelse(pop_size_quant2==1, "County Forecasts: Size Quantile 1",
                                 ifelse(pop_size_quant2==2, "County Forecasts: Size Quantile 2",
                                        ifelse(pop_size_quant2==3, "County Forecasts: Size Quantile 3", 
                                               ifelse(pop_size_quant2==4, "County Forecasts: Size Quantile 4", "County forecasts: Size Quantile 5")))))
}

 
 stop_date <-as.Date("2021-12-21")
 cut_date <-as.Date("2021-12-21")
```

## Supplemental Figures

### Supplement 3: Non large country figures

#### Figure 1. Mean WIS and Mean 95% Coverage

```{r fig s3.1, echo=FALSE, warning=FALSE, message=FALSE, fig.height=8, fig.width=20}

## WIS estimates

mean_WIS <-function() {
  ## Large counties
  load("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts/Data/WIS_all horizons_large counties.rdata")

  WIS_counties <-WIS_all %>%
    filter(type=="quantile") %>%
    summarise_scores(by = c("model"),
                     metric="interval_score",
                     relative_skill = TRUE,
                     baseline = "COVIDhub-baseline") %>%
    dplyr::select(model, scaled_rel_skill) %>%
    distinct() %>%
    mutate(pop_size_quant2="County Forecasts: Size Quantile 5",
           model_reorder=fct_reorder(model, scaled_rel_skill))
  levels_model <-levels(WIS_counties$model_reorder)

  ## Non Large counties
  load("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts/Data/WIS_all horizons_non large counties_all subs.rdata")
  
  WIS_counties_other <-WIS_all %>%
    filter(type=="quantile") %>%
    summarise_scores(by = c("model", "pop_size_quant2"),
                     metric="interval_score",
                     relative_skill = TRUE,
                     baseline = "COVIDhub-baseline") %>%
    dplyr::select(model, scaled_rel_skill, pop_size_quant2) %>%
    distinct() %>%
    rename_counts() %>%
    add_row(model="FRBSF_Wilson-Econometric", pop_size_quant2="County Forecasts: Size Quantile 1") %>% #,
    add_row(model="UMass-MechBayes", pop_size_quant2="County Forecasts: Size Quantile 1") %>% #, 
    add_row(model="UMass-MechBayes", pop_size_quant2="County Forecasts: Size Quantile 2") %>% #, 
    add_row(model="UMass-MechBayes", pop_size_quant2="County Forecasts: Size Quantile 3") %>% #, 
    add_row(model="UMass-MechBayes", pop_size_quant2="County Forecasts: Size Quantile 4") %>% 
    mutate(model_reorder=model) %>%
    mutate(model_reorder=factor(model, levels_model)) 
  
  mean_WIS <-WIS_counties %>%
    bind_rows(., WIS_counties_other) %>%
    mutate(key=pop_size_quant2) %>%
    mutate(value_display=format(round(scaled_rel_skill, digits=2), nsmall = 2),
           value_display=ifelse(value_display=="  NA", NA, value_display)) 
  
  }
mean_WIS <-mean_WIS() 
mean_WIS$model_reorder <-fct_rev(mean_WIS$model_reorder)
levels_model <-levels(mean_WIS$model_reorder)

WIS.heatmap <-mean_WIS %>%
  ungroup() %>%
  ggplot(., aes(key, model_reorder)) +
  geom_tile(aes(fill=scaled_rel_skill)) +
  geom_text(aes(label=value_display), size=3.5) +
  scale_fill_gradient2(low = "steelblue", high = "red", midpoint = 1.0, na.value = "grey75") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width=15)) +
  theme_bw() +
  labs(fill="Relative Weighted Interval Score") +
  theme(axis.title.x = element_blank(), axis.text.y=element_blank(),
        axis.title.y = element_blank(), axis.text=axis.text_standard,
        legend.position="bottom")


############################################################################
############################################################################

### Coverage estimates

cov.95 <-function() {
  load("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts/Data/cases_large counties_forecasts_for analysis_2022-08-18.Rdata")
  
  ## Large counties
  coverage_counties <- dat_large_count %>%
    filter(sub_date <= cut_date) %>%
    coverage(df=.) %>%
    group_by(model) %>%
    summarize(mean_count=mean(coverage.95)) %>%
    mutate(pop_size_quant2="County Forecasts: Size Quantile 5")
  
  load("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts/Data/cases_non large counties_forecasts_for analysis_2022-08-18.Rdata")
  
  ## Non Large counties
  coverage_counties_other <- dat_other_count %>%
    coverage(df=.) %>%
    group_by(model, pop_size_quant2) %>%
    summarize(mean_count=mean(coverage.95)) %>%
    ungroup() 
  
  cov.95 <-coverage_counties %>%
    bind_rows(., coverage_counties_other) %>%
    mutate(value_display=format(round(mean_count, digits=2), nsmall = 2),
           value_display=ifelse(value_display=="  NA", NA, value_display))
}
cov.95 <-cov.95() %>%
  rename_counts() %>%
  ungroup() %>%
  mutate(key=pop_size_quant2) %>%
  add_row(model="FRBSF_Wilson-Econometric", key="County Forecasts: Size Quantile 1") %>% #, 
  add_row(model="UMass-MechBayes", key="County Forecasts: Size Quantile 1") %>% #, 
  add_row(model="UMass-MechBayes", key="County Forecasts: Size Quantile 2") %>% #, 
  add_row(model="UMass-MechBayes", key="County Forecasts: Size Quantile 3") %>% #, 
  add_row(model="UMass-MechBayes", key="County Forecasts: Size Quantile 4") %>%
  mutate(model_reorder=factor(model, levels_model))

cov.heatmap <-cov.95 %>%
  ggplot(., aes(key, model_reorder)) +
  geom_tile(aes(fill=mean_count)) +
  geom_text(aes(label=value_display), size=3.5) +
  scale_fill_gradient2(low = "white", mid = "#f7fcb9", high = "#31a354", midpoint = 0.75, na.value = "grey75") +
  scale_x_discrete(labels = function(x) str_wrap(x, width=15)) +
  theme_bw() +
  labs(fill="95% Coverage") +
  theme(axis.title.x = element_blank(), 
        axis.title.y = element_blank(), axis.text.y=element_blank(),
        axis.text=axis.text_standard,
        legend.position="bottom")

############################################################################
############################################################################

### Submissions over time

submissions <-function(df) {
  
  start_date <-as.Date("2020-07-28")
  stop_date <-as.Date("2021-12-21")
  
  df <-df %>%
    filter(sub_date >= start_date & sub_date <= stop_date) %>% 
    dplyr::select(forecast_date, model, location, target, sub_date, pop_size_quant2) %>%
    distinct() %>%
    dplyr::select(-target) %>%
    distinct() %>%
    group_by(sub_date, model, pop_size_quant2) %>%
    summarize(locs=n()) %>%
    ungroup() %>%
    mutate(total_sub=length(unique(sub_date))) %>%
    group_by(model, pop_size_quant2) %>%
    mutate(wks_sub=length(sub_date),
           per_sub=(wks_sub/total_sub)) %>%
    ungroup() %>%
  dplyr::select(-locs, -sub_date) %>%
  distinct()
  
  return(df)
  
}

load("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts/Data/cases_large counties_forecasts_for analysis_2022-08-18.Rdata")
subs_co <-submissions(df=dat_large_count) %>%
  mutate(pop_size_quant2="County Forecasts: Size Quantile 5")

load("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts/Data/cases_non large counties_forecasts_for analysis_2022-08-18.Rdata")
subs_co_other <-submissions(df=dat_other_count) %>%
  rename_counts()


all_subs <-subs_co %>%
  bind_rows(., subs_co_other) %>%
  mutate(key=pop_size_quant2,
         value_display=format(round(per_sub, digits=2), nsmall = 2),
         value_display=ifelse(value_display=="  NA", NA, value_display)) %>%
  ungroup() %>%
  add_row(model="FRBSF_Wilson-Econometric", key="County Forecasts: Size Quantile 1") %>%  
  add_row(model="UMass-MechBayes", key="County Forecasts: Size Quantile 1") %>% 
  add_row(model="UMass-MechBayes", key="County Forecasts: Size Quantile 2") %>% 
  add_row(model="UMass-MechBayes", key="County Forecasts: Size Quantile 3") %>% 
  add_row(model="UMass-MechBayes", key="County Forecasts: Size Quantile 4") %>%
  mutate(model_reorder=factor(model, levels_model)) %>%
  ggplot(., aes(key, model_reorder)) +
  geom_tile(aes(fill=per_sub)) +
  geom_text(aes(label=value_display), size=3.5) +
  scale_fill_gradient(low = "#fde0dd", high = "#c51b8a", na.value = "grey75") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width=15)) +
  theme_bw() +
  labs(fill="% Weeks \nSubmitted") +
  theme(axis.title.x = element_blank(),   
        axis.title.y = element_blank(), 
        axis.text=axis.text_standard,
        legend.position="bottom")

############################################################################
############################################################################

plot_grid(all_subs, WIS.heatmap, cov.heatmap,
          rel_widths = c(0.95, 0.70, 0.66),
          nrow=1) 

```

