---
title: "Supplement 1A"
author: "VKL"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning=FALSE,message=FALSE) 

library(here)
library(tidyverse)
library(tidytext)
library(ggrepel)

library(gridExtra)

library(scoringutils)
library(viridis)

library(ggeffects)
library(emmeans)
library(splines)

## Standardized formatting
strip.background_standard <-element_blank()
strip.text_standard <-element_text(size=10, face='bold')
legend.text_standard <-element_text(size=12)
plot.caption_standard <-element_text(size=11, face = "italic")
axis.title.y_standard <-element_text(margin = margin(1, 10, 1, 1), size=12)
axis.text_standard <-element_text(size=11)

## Change labels for counties
 rename_counts <-function(df) {   
   df <-df %>%
     mutate(pop_size_quant2=ifelse(pop_size_quant2==1, "County Forecasts: Size Quantile 1",
                                 ifelse(pop_size_quant2==2, "County Forecasts: Size Quantile 2",
                                        ifelse(pop_size_quant2==3, "County Forecasts: Size Quantile 3", 
                                               ifelse(pop_size_quant2==4, "County Forecasts: Size Quantile 4", "County forecasts: Size Quantile 5")))))
}

```

## Supplemental Figures

### Supplement 1

```{r Fig S1A, echo=FALSE, warning=FALSE, message=FALSE, fig.height=8, fig.width=11}
start_date <-as.Date('2020-07-28')
stop_date <-as.Date('2021-12-21')

sec_models <-c("CU-nochange",  "CU-scenario_high", "CU-scenario_low", "CU-scenario_mid", "COVIDhub_CDC-ensemble") ## Non-primary models should be exlcuded

## Must have 4 weeks of forecasts for all locations
include_wks <-function(x, df){
  
  df <-df %>%
    group_by(model, sub_date, location) %>%
    mutate(no_horizons=length(unique(target))) %>% 
    ungroup() %>%
    filter(no_horizons>=4) #There should be at least 4 horizons
}

## Must have quantities for all forecasts
include_quant <-function(x, df){
  
  df <-df %>%
    group_by(model, location, forecast_date, target) %>%
    mutate(quants=length(quantile[!is.na(quantile)])) %>%
    ungroup() %>%
    filter(quants==7) #There should be 7 quantiles 
  
}

## Must have forecasts for at least 50 locations for states/territories/district and national
include_locs <-function(x, df){
  
  df <-df %>%
    mutate(location=as.factor(location)) %>%
    group_by(model, forecast_date) %>%
    mutate(locs=length(unique(location))) %>% #[quantile==0.5 & target=="1 wk ahead inc case"]))) %>%
    ungroup() %>%
    filter(locs>=50) 
  
}

## Must have 75% of all counties per quantile per submission date forecasted
include_locs_co <-function(x, df){
  
  df <-df %>%
    group_by(pop_size_quant2) %>%
    mutate(locs_total=length(unique(location))) %>% 
    ungroup() %>%
    group_by(model, pop_size_quant2, sub_date) %>%
    mutate(locs=length(unique(location))) %>% #[quantile==0.5 & target=="1 wk ahead inc case"]))) %>%
    ungroup() %>%
    mutate(percent_co=locs/locs_total) %>%
    filter(percent_co>=0.75)
}

## Must have submitted at least 50% of weeks
include_subs <-function(x, df){
  
  df <-df %>%
    filter(sub_date >= start_date) %>%
    mutate(total=length(unique(sub_date))) %>% 
    group_by(model) %>%
    mutate(subs=length(unique(sub_date))) %>%
    ungroup() %>%
    mutate(percent_sub=subs/total) %>%
    filter(percent_sub>=0.50)
  
}

############################################################################
############################################################################

load(here("Data/Submitted_cases_county_forecasts.Rdata"))

### National + state submissions
nat_st <-all_dat %>%
  filter(!(model %in% sec_models),
         sub_date >= start_date & sub_date <= stop_date) %>%
  filter(type=="point")

### National + state submissions that met inclusion criteria
teams_nat_st <-all_dat %>%
  filter(!(model %in% sec_models),
         sub_date >= start_date & sub_date <= stop_date) %>%
  include_quant(df=.) %>% #all quantiles present
  include_wks(df=.) %>% #all targets included 
  include_locs(df=.) %>% #at least 50 locations
  include_subs(df=.) %>% #submitted at least 50% of the time
  dplyr::select(model) %>%
  mutate(model_rename=paste0("*", model)) %>%
  distinct()

### Submission plots

nat_st %>%
  dplyr::select(-target, -target_end_date, -value) %>%
  distinct() %>%
  group_by(sub_date, model) %>%
  summarize(locs=n()) %>%
  ungroup() %>%
  mutate(log_loc=log(locs)) %>%
  ungroup() %>%
  mutate(total_sub=length(unique(sub_date))) %>%
  group_by(model) %>%
  mutate(wks_sub=length(sub_date),
         per_sub=wks_sub/total_sub) %>%
  ungroup() %>%
  left_join(., teams_nat_st, by="model") %>%
  mutate(model_rename=ifelse(is.na(model_rename), model, model_rename),
         model_rename=fct_reorder(model_rename, wks_sub)) %>%
  ggplot(., aes(sub_date, model_rename)) +
  geom_tile(aes(fill=log_loc)) +
  scale_fill_gradient(low = "#c7e9c0", high = "#41ab5d",
                      name = "Number of \nlocations forecasted", 
                      breaks = c(0, 3.9), 
                      labels =c(1, 50)
                      ) + 
 # geom_text(aes(label=locs), size=1.50) +
  scale_x_date(date_breaks = "1 month", date_minor_breaks = "1 week", date_labels = "%B") +
  theme_bw() +
  labs(title = "A. Primary Model* Submissions for National/State/Territory-Level Case Forecasts Over Time",
       #subtitle= "The number of locations forecasted per submission is labled"#,
       caption = "*Model met inclusion criteria"
       ) +
  theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 45, hjust=1),
        axis.title.y = element_blank(),
        legend.position = "bottom", legend.title.align=0.5)

```
