---
title: "Supplement 5"
author: "VKL"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning=FALSE,message=FALSE) 

library(tidyverse)
library(tidytext)
library(ggrepel)

library(gridExtra)
library(cowplot)
library(ggpubr)
library(scoringutils)
library(viridis)

library(ggeffects)
library(emmeans)
library(splines)

setwd("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts")

### Need functions
source("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts/Code/Inc_Case_Eval_Manuscript/coverage.R") #coverage

## Standardized formatting
strip.background_standard <-element_blank()
strip.text_standard <-element_text(size=10, face='bold')
legend.text_standard <-element_text(size=12)
plot.caption_standard <-element_text(size=11, face = "italic")
axis.title.y_standard <-element_text(margin = margin(1, 10, 1, 1), size=12)
axis.text_standard <-element_text(size=11)

 stop_date <-as.Date("2021-12-21")
 cut_date <-as.Date("2021-12-21")
 
```

## Supplemental Figures

### Supplement 5: Horizon specific plots

####  Coverage.

```{r, echo=FALSE, warning=F, message=F, fig.show='hide'}

# Read in and manipulate data + plot structure
cov.fig_dat <-function(df) {
  coverage <-df %>%
    coverage(df=.) %>%
    group_by(model, target) %>%
    summarize(coverage.95=mean(coverage.95),
              coverage.80=mean(coverage.80),
              coverage.50=mean(coverage.50)) %>%
    gather("expected_cov", "observed_cov", coverage.95:coverage.50) %>%
    mutate(expected_cov=gsub("coverage.", "", expected_cov),
           expected_cov=as.numeric(expected_cov),
           expected_cov=expected_cov/100,
           bold=ifelse(model=="COVIDhub-baseline" | model=="COVIDhub-4_week_ensemble", "T", "F"),
          grouping=ifelse(model=="COVIDhub-baseline", "COVIDhub-baseline", 
                           ifelse(model=="COVIDhub-4_week_ensemble", "COVIDhub-4_week_ensemble", "Other teams")))
  return(coverage)
}
data_labels <-function(df) {
  
  ensemble_cov1 <-df %>%
    filter(model=="COVIDhub-4_week_ensemble",
           grepl("1",target))
  
  ensemble_cov4 <-df %>%
    filter(model=="COVIDhub-4_week_ensemble",
           grepl("4",target))
  
  data_labels1 <-df %>%  
    filter(model!="COVIDhub-4_week_ensemble",
           grepl("1",target)) %>%
    mutate(test_95=ifelse(expected_cov==0.95 & observed_cov > ensemble_cov1$observed_cov[ensemble_cov1$expected_cov==0.95], 1, NA),
           test_80=ifelse(expected_cov==0.80 & observed_cov > ensemble_cov1$observed_cov[ensemble_cov1$expected_cov==0.80], 1, NA),
           test_50=ifelse(expected_cov==0.50 & observed_cov > ensemble_cov1$observed_cov[ensemble_cov1$expected_cov==0.50], 1, NA)) %>%
    filter(!is.na(test_95) | !is.na(test_80) | !is.na(test_50)) %>%
    group_by(model) %>%
    mutate(model_count=n()) %>%
    filter(model_count==3 & expected_cov==0.95) %>%
    mutate(model=ifelse(model=="JHU_UNC_GAS-StatMechPool", "JHU_UNC_GAS\n-StatMechPool", model)) %>%
    #mutate(model=ifelse(model=="MOBS-GLEAM_COVID", "MOBS-GLEAM_\nCOVID", model)) %>%
    mutate(model=ifelse(model=="IEM_MED-CovidProject", "IEM_MED\n-CovidProject", model)) %>%
    mutate(model=ifelse(model=="COVIDhub-trained_ensemble", "COVIDhub\n-trained\n_ensemble", model)) 
  
  data_labels4 <-df %>%  
    filter(model!="COVIDhub-4_week_ensemble",
           grepl("4",target)) %>%
    mutate(test_95=ifelse(expected_cov==0.95 & observed_cov > ensemble_cov4$observed_cov[ensemble_cov4$expected_cov==0.95], 1, NA),
           test_80=ifelse(expected_cov==0.80 & observed_cov > ensemble_cov4$observed_cov[ensemble_cov4$expected_cov==0.80], 1, NA),
           test_50=ifelse(expected_cov==0.50 & observed_cov > ensemble_cov4$observed_cov[ensemble_cov4$expected_cov==0.50], 1, NA)) %>%
    filter(!is.na(test_95) | !is.na(test_80) | !is.na(test_50)) %>%
    group_by(model) %>%
    mutate(model_count=n()) %>%
    filter(model_count==3 & expected_cov==0.95) %>%
    mutate(model=ifelse(model=="JHU_UNC_GAS-StatMechPool", "JHU_UNC_GAS\n-StatMechPool", model)) %>%
    #mutate(model=ifelse(model=="MOBS-GLEAM_COVID", "MOBS-GLEAM_\nCOVID", model)) %>%
    mutate(model=ifelse(model=="IEM_MED-CovidProject", "IEM_MED\n-CovidProject", model)) %>%
    mutate(model=ifelse(model=="COVIDhub-trained_ensemble", "COVIDhub\n-trained\n_ensemble", model)) 
  
  data_labels <-bind_rows( data_labels1,  data_labels4)
  
  return(data_labels)
  }
cov.plot <-function(df, df2) {
  ggplot(df) +
    geom_line(data=filter(df, bold=="F"), 
              mapping=aes(expected_cov, observed_cov, group=model, color=grouping, size=bold, alpha=0.75)) +
    geom_point(data=filter(df, bold=="F"), 
               mapping=aes(expected_cov, observed_cov, group=model, color=grouping), size=1.5) +
    geom_line(data=filter(df, bold=="T"), 
              mapping=aes(expected_cov, observed_cov, group=model, color=grouping, size=bold, alpha=0.75)) +
    geom_point(data=filter(df, bold=="T"), 
               mapping=aes(expected_cov, observed_cov, group=model, color=grouping), size=3) +
    geom_line(aes(expected_cov, expected_cov, color=grouping, group=model), linetype="dashed", size=1.5, color="black") +
    scale_size_manual(values = c("T"=1.5, "F"=0.85)) +
    scale_colour_manual(values = c("COVIDhub-baseline"="#762a83",
                                   "COVIDhub-4_week_ensemble"="#1b7837",
                                   "Other teams"="grey70"),
                        labels=c("Other teams", "COVIDhub-baseline", "COVIDhub-4_week\n_ensemble"),
                        breaks=c("Other teams", "COVIDhub-baseline", "COVIDhub-4_week_ensemble")) +
    guides(size = "none", alpha="none") +
    labs(y="Observed Coverage") +
    theme_bw()  + 
    theme(legend.position = "none", 
          axis.title.x = element_blank()) +
    geom_text_repel(data=df2,
                    mapping=aes(expected_cov, observed_cov, label=model), size=3,
                    force=1, point.padding=unit(0.5,'lines'), nudge_x =0.1,
                    segment.size= 0.05,  segment.color="grey50",
                    direction="y", #hjust = "right",
                    vjust=0.5) +
    scale_x_continuous(expand = expansion(mult = c(0.05, 0.25)))
}

# Figures

load("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts/Data/cases_nat_state_forecasts_for analysis_2022-08-18.Rdata")

coverage_US <-cov.fig_dat(filter(dat_US_state, location=="US", sub_date <= cut_date,
                                   !grepl("2", target),
                                   !grepl("3", target)))
labels_US <-data_labels(coverage_US)
Cov.Nat <-cov.plot(coverage_US, labels_US) +
  facet_wrap(~target) +
  theme(legend.position = c(0.02, 0.85), legend.title = element_blank(),
        legend.justification = c(0, 0.5), 
        legend.margin=margin(c(0.5,1,1,1)),
        legend.key = element_rect(colour = NA, fill = NA),
        strip.text=strip.text_standard, strip.background=strip.background_standard) +
  labs(title="A. Coverage for National Forecasts")

coverage_states <-cov.fig_dat(filter(dat_US_state, location!="US", sub_date <= cut_date,
                                   !grepl("2", target),
                                   !grepl("3", target)))
labels_states <-data_labels(coverage_states)
Cov.State <-cov.plot(coverage_states, labels_states) +
  facet_wrap(~target) +
  theme(strip.text=strip.text_standard, strip.background=strip.background_standard) +
  labs(title="B. Coverage for National State/Territory/DC Forecasts")

# Largest Counties
load("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts/Data/cases_large counties_forecasts_for analysis_2022-08-18.Rdata")
coverage_count <-cov.fig_dat(filter(dat_large_count, sub_date <= cut_date,
                                   !grepl("2", target),
                                   !grepl("3", target)))
labels_count <-data_labels(coverage_count) 
Cov.Co <-cov.plot(coverage_count, labels_count) +
  facet_wrap(~target) +
  theme(strip.text=strip.text_standard, strip.background=strip.background_standard) +
  labs(title="C. Coverage for Large County Forecasts*",
       x="Expected Coverage")

```

```{r Fig S5.1, echo=FALSE, warning=F, message=F, fig.height=12, fig.width=12}

annotate_figure(
  grid.arrange(Cov.Nat, Cov.State, Cov.Co, ncol=1),
 bottom = text_grob("*U.S. counties with a population of at least 93,230 people ", hjust=1, x=1, face = "italic", size = 10))

```

####  Absolute WIS

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.show='hide'}

# Function for WIS over time
WIS.ot.fig_dat <-function(df) {
  
  sub_date <-c(unique(df$sub_date))
  model <-c(as.character(unique(df$model)))
  model_dates <-crossing(sub_date, model)
  
  cast_dates <-df %>%
    dplyr::select(sub_date, date, target) %>%
    distinct() %>%
    left_join(model_dates, by="sub_date")
  
  dat <-df %>%
    full_join(cast_dates, ., by=c("model", "sub_date", "date", "target")) %>%
    mutate(bold=ifelse(model=="COVIDhub-baseline" | model=="COVIDhub-4_week_ensemble", "T", "F")) %>%
    group_by(model, date, bold, target) %>%
    summarize(abWIS=mean(interval_score, na.rm=TRUE)) %>%
    ungroup() %>%
    mutate(grouping=ifelse(model=="COVIDhub-baseline", "COVIDhub-baseline", 
                           ifelse(model=="COVIDhub-4_week_ensemble", "COVIDhub-4_week_ensemble", "Other teams"))) #%>%
  return(dat)

}
cov.ot.fig_dat <-function(df) {
  
  sub_date <-c(unique(df$sub_date))
  model <-c(as.character(unique(df$model)))
  model_dates <-crossing(sub_date, model)
  
  cov <-df %>%
    group_by(model, target_end_date, target) %>%
    coverage(df=.) %>%
    summarize(cov.95=mean(coverage.95))

  dat <-df %>%
    dplyr::select(sub_date, target_end_date, target) %>%
    distinct() %>%
    left_join(., model_dates, by=c("sub_date")) %>%
    dplyr::select(-sub_date) %>%
    left_join(., cov, by=c("model", "target_end_date", "target")) %>%
    distinct() %>%
    ungroup() %>%
    mutate(grouping=ifelse(model=="COVIDhub-baseline", "COVIDhub-baseline", 
                           ifelse(model=="COVIDhub-4_week_ensemble", "COVIDhub-4_week_ensemble", "Other teams"))) %>%
    mutate(bold=ifelse(model=="COVIDhub-baseline" | model=="COVIDhub-4_week_ensemble", "T", "F")) 
  
  return(dat)

}
ot.plot <-function(df, x, y) {
  
  ggplot() +
    geom_line(data=filter(df, bold=="F"), mapping=aes({{x}}, {{y}}, group=model, color=grouping, size=bold)) +
    geom_point(data=filter(df, bold=="F"), mapping=aes({{x}}, {{y}}, group=model, color=grouping, size=bold)) +
    geom_line(data=filter(df, bold=="T"), mapping=aes({{x}}, {{y}}, group=model, color=grouping, size=bold)) +
    geom_point(data=filter(df, bold=="T"), mapping=aes({{x}}, {{y}}, group=model, color=grouping, size=bold)) +
    scale_size_manual(values = c("T"=1.25, "F"=0.85)) +
    scale_x_date(date_labels="%b-%y", breaks = df$x, date_breaks ="3 months", date_minor_breaks ="1 month") +
    geom_vline(xintercept = as.numeric(cut_date),  linetype=4, size=1.05) +
    scale_colour_manual(name="",
                        values = c("COVIDhub-baseline"="#762a83",
                                   "COVIDhub-4_week_ensemble"="#1b7837",
                                   "Other teams"="grey80"),
                        labels=c("Other teams", "COVIDhub-baseline", "COVIDhub-4_week_ensemble"),
                        breaks=c("Other teams", "COVIDhub-baseline", "COVIDhub-4_week_ensemble")) +
    guides(size = "none") + 
    theme_bw() +
    theme(legend.position = "none", 
          axis.title.x = element_blank())
}

###########################################################################
############################################################################

### WIS Over time
load("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts/Data/WIS_all horizons_nat_state.Rdata")

## National
WIS_ot_nat <-WIS.ot.fig_dat(filter(WIS_all, location_name=="National",
                                   !grepl("2", target),
                                   !grepl("3", target))) 
Fig2.B <-ot.plot(WIS_ot_nat, date, abWIS)  +
   facet_wrap(~ target) +
  scale_y_continuous(trans='log10') +
  theme(axis.title.x=element_blank(),
        legend.position = c(0.02, 0.80),legend.title = element_blank(),
        legend.justification = c(0, 0.5), 
        legend.margin=margin(c(0.25,0.25,0.25,0.25)),
        legend.key = element_rect(colour = NA, fill = NA),
        strip.text=strip.text_standard, strip.background=strip.background_standard) +
  labs(title="A. Average Weighted Interval Score for National Forecasts",
       y = "Average Weighted Interval Score") +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.35))) + 
  theme(axis.text.y=element_text(angle=90, vjust=0.5, hjust=0.5))
  

## State/Territory/District
WIS_ot_state <-WIS.ot.fig_dat(filter(WIS_all, location_name!="National",
                                     location_name!="American Samoa",
                                     !grepl("2", target),
                                     !grepl("3", target))) 
Fig2.C <-ot.plot(WIS_ot_state, date, abWIS) +
   facet_wrap(~ target) +
  theme(strip.text=strip.text_standard, strip.background=strip.background_standard) +
  scale_y_continuous(trans='log10') +
  labs(title = "B. Average Weighted Interval Score for State/Territory/DC Forecasts",
       y = "Average Weighted Interval Score") + theme(axis.text.y=element_text(angle=90, vjust=0.5, hjust=0.5))

## Large Counties
load("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts/Data/WIS_all horizons_large counties.Rdata")
WIS_ot_co <-WIS.ot.fig_dat(filter(WIS_all, 
                                  !grepl("2", target),
                                  !grepl("3", target))) 
Fig2.D <-ot.plot(WIS_ot_co, date, abWIS) +
  facet_wrap(~ target) +
  theme(strip.text=strip.text_standard, strip.background=strip.background_standard) +
  scale_y_continuous(trans='log10') +
  labs(title = "C. Average Weighted Interval Score for Large County Forecasts*",
       x = "Forecast target date",
       y = "Average Weighted Interval Score") + 
  theme(axis.text.y=element_text(angle=90, vjust=0.5, hjust=0.5))

############################################################################
############################################################################

### Coverage Over time

load("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts/Data/cases_nat_state_forecasts_for analysis_2022-08-18.Rdata")
load("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts/Data/cases_large counties_forecasts_for analysis_2022-08-18.Rdata")

## National
cov_ot_nat <-cov.ot.fig_dat(filter(dat_US_state, location=="US", sub_date <= cut_date,
                                  !grepl("2", target),
                                  !grepl("3", target)))
Fig2.F <-ot.plot(cov_ot_nat, target_end_date, cov.95)  +
  geom_hline(yintercept = 0.95,  linetype=6, size=1.05) +
  facet_wrap(~ target) +
  theme(axis.title.x=element_blank()) +  
  labs(title="D. 95% Coverage for National Forecasts",
       y = "95% Coverage") + 
  theme(strip.text=strip.text_standard, strip.background=strip.background_standard,
        axis.text.y=element_text(angle=90, vjust=0.5, hjust=0.5))

## State/Territory/District
cov_ot_state <-cov.ot.fig_dat(filter(dat_US_state, location!="US", sub_date <= cut_date, 
                                  !grepl("2", target),
                                  !grepl("3", target)))
Fig2.G <-ot.plot(cov_ot_state, target_end_date, cov.95) +
  facet_wrap(~ target) +
  geom_hline(yintercept = 0.95,  linetype=6, size=1.05) +
  labs(title = "E. 95% Coverage for State/Territory/DC Forecasts",
       y = "95% Coverage") + 
    theme(strip.text=strip.text_standard, strip.background=strip.background_standard,
        axis.text.y=element_text(angle=90, vjust=0.5, hjust=0.5))
## Large Counties
cov_ot_co <-cov.ot.fig_dat(filter(dat_large_count, sub_date <= cut_date, 
                                  !grepl("2", target),
                                  !grepl("3", target)))
Fig2.H <-ot.plot(cov_ot_co, target_end_date, cov.95) +
  facet_wrap(~ target) +
  geom_hline(yintercept = 0.95,  linetype=6, size=1.05) +
  labs(title = "F. 95% Coverage for Large County Forecasts*",
       x = "Forecast target date",
       y = "95% Coverage") +  
  theme(strip.text=strip.text_standard, strip.background=strip.background_standard,
        axis.text.y=element_text(angle=90, vjust=0.5, hjust=0.5))

```

```{r Fig S5.2, echo=FALSE, warning=FALSE, message=FALSE, fig.height=11, fig.width=12}

annotate_figure(
  grid.arrange(Fig2.B, Fig2.F,
             Fig2.C, Fig2.G,
             Fig2.D, Fig2.H,
             ncol=2),
          bottom = text_grob("*U.S. counties with a population of at least 93,230 people ", hjust=1, x=1, face = "italic", size = 10))

```

### Relative WIS

```{r Fig S5.3, echo=FALSE, warning=FALSE, message=FALSE, fig.height=10, fig.width=12.5}

# Forecasts
load("C:/Users/oko8/OneDrive - CDC/COVID/Forecasts/Data/WIS_all horizons_nat_state.Rdata")

###
relWIS <-WIS_all %>%
  filter(!grepl("2", target),
         !grepl("3", target)) %>%
  filter(type=="quantile") %>%
    summarise_scores(by = c("model", "location_name", "target"),
                     metric="interval_score",
                     relative_skill = TRUE,
                     baseline = "COVIDhub-baseline") %>%
  mutate(scaled_rel_skill=round(scaled_rel_skill, 1),
         log_WIS=log2(scaled_rel_skill),
         location_name=as.character(location_name)) 

###
levels_model <-WIS_all %>%
  filter(type=="quantile") %>%
    summarise_scores(by = c("model"),
                     metric="interval_score",
                     relative_skill = TRUE,
                     baseline = "COVIDhub-baseline") %>%
    ungroup() %>% 
  mutate(model_reorder = fct_reorder(model, scaled_rel_skill, .desc = TRUE)) 
levels_model <-levels(levels_model$model_reorder)

Locations <-relWIS %>%
  dplyr::select(location_name) %>%
  distinct()

Models <-relWIS %>%
  dplyr::select(model, target) %>%
  distinct()

Locations_models <-crossing(Locations, Models) 
relWIS <- Locations_models %>%
  left_join(., relWIS) %>%
  ungroup() %>%
  mutate(model_reorder=factor(model, levels=levels_model))

# Reorder x and y axes
relWIS$location_name <-as.factor(relWIS$location_name)
relWIS$location_name <-relevel(relWIS$location_name, ref="National")
relWIS$location_name <-fct_rev(relWIS$location_name)

# Figure
ggplot(relWIS, aes(model_reorder, location_name)) +
  geom_tile(aes(fill=log_WIS)) +
  geom_text(aes(label=scaled_rel_skill), size=3) +
  facet_wrap(~target) +
  scale_fill_gradient2(low = "steelblue", high = "red", midpoint = 0, na.value = "grey75", 
                       name = "Relative \nWeighted Interval Score", 
                       breaks = c(-1,0,1,2), 
                       labels =c("0.5", 1, 2, 3)) + 
  theme_bw() +
  labs(fill="Relative \nWeighted Interval Score") +
  theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 45, hjust=1),
        axis.title.y = element_blank(),
        strip.text=strip.text_standard, strip.background=strip.background_standard,
        axis.text=axis.text_standard, plot.caption = plot.caption_standard)


```
